### ISSUE TITLE
kv_role_assigment resource block

### ISSUE THREAD

**Issue by sanyoganurag** [Pwd9000-ML/terraform-azurerm-openai-private-chatgpt#31]
As suggested in comment, null is not being accepted

│ Error: invalid value for scope (Subscription scope is invalid)
│ 
│   with module.privategpt_chatbot_container_apps.azurerm_role_assignment.kv_role_assigment["Key Vault Secrets User"],
│   on modules/container_app/main.tf line 89, in resource "azurerm_role_assignment" "kv_role_assigment":
│   89:   scope                = var.key_vault_id
│ 
╵
╷
│ Error: Cannot parse Azure ID: parse "": empty url
│ 
│   with module.privategpt_chatbot_container_apps.azurerm_role_assignment.kv_role_assigment["Key Vault Secrets User"],
│   on modules/container_app/main.tf line 89, in resource "azurerm_role_assignment" "kv_role_assigment":
│   89:   scope                = var.key_vault_id
│

**Comment by Pwd9000-ML** [comment]
@sanyoganurag Closing this issue down as the module has ben completely reworked with new services to support latest AI features and models
